/* Style direction: Reqly documentation aligned with the real desktop app — dark workspace, emerald actions, simple product language, guided scenarios. */
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowLeft, ArrowRight, Bell, Boxes, Braces, Check, CheckCircle2, ChevronDown, ChevronRight, CircleHelp, Command, Copy, Download, ExternalLink, FileCode2, GitBranch, Github, Globe, KeyRound, Layers3, Menu, Monitor, Play, Search, Shield, Sparkles, Table2, Terminal, Upload, WifiOff, Workflow, X, Zap } from "lucide-react";
import { toast } from "sonner";

const asset = {
  mark: "/manus-storage/reqly-official-icon_b6b34e2f.png",
  hero: "/manus-storage/reqly-reference_474512e2.png",
  orbit: "/manus-storage/reqly-collection-orbit-v2_3aa81a5d.png",
};

type Page = { slug: string; label: string; group: string; description: string; kicker: string; time: string };
const pages: Page[] = [
  { slug: "overview", label: "Découvrir Reqly", group: "COMMENCER", description: "Comprendre l’essentiel avant de se lancer.", kicker: "POINT DE DÉPART", time: "3 min" },
  { slug: "quickstart", label: "Faire son premier essai", group: "COMMENCER", description: "Voir une idée prendre vie en quelques minutes.", kicker: "PARCOURS 01", time: "6 min" },
  { slug: "requests", label: "Préparer un appel", group: "TRAVAILLER", description: "Choisir une méthode, régler l’auth et le corps, lire la réponse.", kicker: "PARCOURS 02", time: "8 min" },
  { slug: "environments", label: "Changer d’espace", group: "TRAVAILLER", description: "Passer d’un espace de travail à l’autre sans tout refaire.", kicker: "PARCOURS 03", time: "5 min" },
  { slug: "collections", label: "Garder ses idées ensemble", group: "TRAVAILLER", description: "Retrouver facilement ce que tu as déjà préparé.", kicker: "PARCOURS 04", time: "7 min" },
  { slug: "assertions", label: "Vérifier le résultat", group: "COMPRENDRE", description: "Savoir rapidement si tout s’est bien passé.", kicker: "PARCOURS 05", time: "6 min" },
  { slug: "runs", label: "Rejouer un scénario", group: "COMPRENDRE", description: "Vérifier une collection entière en une seule passe.", kicker: "PARCOURS 06", time: "5 min" },
  { slug: "integrations", label: "Partager avec ton équipe", group: "CONNECTER", description: "Importer, exporter et continuer ensemble.", kicker: "PARCOURS 07", time: "9 min" },
  { slug: "ai", label: "Demander un coup de main", group: "CONNECTER", description: "Comprendre ou débloquer une situation.", kicker: "PARCOURS 08", time: "4 min" },
  { slug: "desktop", label: "Travailler sur ordinateur", group: "ALLER PLUS LOIN", description: "Profiter du confort du bureau, même sans réseau.", kicker: "À RETENIR 09", time: "6 min" },
  { slug: "reqly-json", label: "Sauvegarder son travail", group: "ALLER PLUS LOIN", description: "Garder une copie et la transmettre facilement.", kicker: "À RETENIR 10", time: "5 min" },
];
const groups = ["COMMENCER", "TRAVAILLER", "COMPRENDRE", "CONNECTER", "ALLER PLUS LOIN"];

function getPage(slug: string) { return pages.find((page) => page.slug === slug) ?? pages[0]; }
function PageGlyph({ slug }: { slug: string }) {
  if (slug === "quickstart" || slug === "runs") return <Play size={13} />;
  if (slug === "requests" || slug === "reqly-json") return <Terminal size={13} />;
  if (slug === "environments" || slug === "collections") return <Layers3 size={13} />;
  if (slug === "assertions") return <CheckCircle2 size={13} />;
  if (slug === "ai") return <Sparkles size={13} />;
  return <FileCode2 size={13} />;
}

function RequestLab() {
  const [sent, setSent] = useState(false);
  return <div className="request-lab"><div className="lab-head"><span className="lab-light" /><span className="lab-light yellow" /><span className="lab-light lime" /><span className="lab-title">PREMIER ESSAI</span><span className="lab-live">GUIDÉ</span></div><div className="lab-request"><div className="lab-row"><select className="demo-choice" defaultValue="GET" aria-label="Méthode"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select><input aria-label="Adresse à appeler" defaultValue="https://api.exemple.com/projets" /></div><div className="lab-tabs"><button className="active">Préparer <span>1</span></button><button>Regarder</button><button>Comprendre</button></div><div className="lab-grid"><div><div className="lab-caption">CE QUE TU VEUX FAIRE</div><div className="lab-kv"><code>Espace</code><code>Mon espace</code></div><div className="lab-kv"><code>Environnement</code><code>Local</code></div><div className="lab-kv"><code>Auth</code><code>Aucune</code></div><button className="send-request" onClick={() => { setSent(false); window.setTimeout(() => setSent(true), 400); }}><Play size={14} fill="currentColor" /> Exécuter</button></div><div className={`lab-response ${sent ? "is-live" : ""}`}><div className="lab-caption">CE QUI REVIENT <span>{sent ? "PRÊT À LIRE" : "EN ATTENTE"}</span></div>{sent ? <><CheckCircle2 size={28} /><strong>200 OK · 184 ms · 1,2 ko</strong><p>Statut, temps et taille s’affichent dans le panneau de droite.</p><div className="lab-stats"><span>RÉUSSI</span><span>RAPIDE</span><span>VISIBLE</span></div></> : <><CircleHelp size={24} /><p>Le panneau attend ton premier essai.</p></>}</div></div></div></div>;
}

function DocsSidebar({ slug, search, setSearch, mobileOpen, closeMobile }: { slug: string; search: string; setSearch: (value: string) => void; mobileOpen: boolean; closeMobile: () => void }) {
  const filtered = useMemo(() => pages.filter((page) => `${page.label} ${page.description} ${page.group}`.toLowerCase().includes(search.toLowerCase())), [search]);
  return <aside className={`docs-sidebar ${mobileOpen ? "is-open" : ""}`}><div className="docs-sidebar-top"><Link href="/" className="docs-brand" onClick={closeMobile}><img src={asset.mark} alt="" /><span>REQ<span>LY</span></span></Link><button className="close-mobile" onClick={closeMobile} aria-label="Fermer le menu"><X size={18} /></button></div><label className="docs-search"><Search size={14} /><input id="docs-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Chercher dans les docs" aria-label="Chercher dans les documents" /><kbd>/</kbd></label><div className="docs-sidebar-scroll">{groups.map((group) => { const items = filtered.filter((page) => page.group === group); if (!items.length) return null; return <div className="nav-group" key={group}><div className="nav-group-title"><span>{group}</span><span className="nav-line" /></div>{items.map((page) => <Link key={page.slug} href={`/${page.slug}`} onClick={closeMobile} className={`docs-nav-link ${slug === page.slug ? "active" : ""}`}><span className={`nav-status ${slug === page.slug ? "current" : ""}`} /><PageGlyph slug={page.slug} />{page.label}{slug === page.slug && <ChevronRight size={14} />}</Link>)}</div>; })}</div><div className="docs-sidebar-foot"><div className="side-score"><Sparkles size={14} /><span>PARCOURS</span><strong>{Math.max(1, pages.findIndex((page) => page.slug === slug) + 1)} / {pages.length}</strong><div><i style={{ width: `${Math.max(9, ((pages.findIndex((page) => page.slug === slug) + 1) / pages.length) * 100)}%` }} /></div></div><a href="https://github.com/kevsi/reqly-v1" target="_blank" rel="noreferrer"><Github size={14} /> Voir le dépôt <ExternalLink size={12} /></a></div></aside>;
}

function DocsTopbar({ page, setMobileOpen }: { page: Page; setMobileOpen: (value: boolean) => void }) {
  return <header className="docs-topbar"><button className="open-mobile" onClick={() => setMobileOpen(true)} aria-label="Ouvrir la navigation"><Menu size={20} /></button><div className="docs-crumb"><span>DOCUMENTATION</span><ChevronRight size={13} /><strong>{page.group}</strong><ChevronRight size={13} /><b>{page.label}</b></div><div className="workspace-context"><span className="workspace-name"><i /> Mon espace</span><span className="env-chip">Local <ChevronDown size={12} /></span><span className="context-button"><Layers3 size={12} /> Variables</span></div><div className="docs-top-actions"><span className="docs-version"><i /> v0.1.0 · OPEN SOURCE</span><Link href="/quickstart" className="top-quick">Démarrer <ArrowRight size={14} /></Link></div></header>;
}

function PageHeader({ page }: { page: Page }) { return <div className="page-header"><div className="page-header-kicker"><span>{page.kicker}</span><span className="reading-time">{page.time} DE LECTURE</span></div><h1>{page.label}</h1><p>{page.description} {page.slug === "overview" ? "Reqly est un client API qui réunit REST, GraphQL et SSE dans une même fenêtre." : "Tu peux suivre ce parcours à ton rythme, sans avoir besoin de tout connaître à l’avance."}</p></div>; }

function Overview() { return <><div className="overview-hero"><div><div className="mission-badge"><span>POINT DE DÉPART</span><i /> SANS PRÉREQUIS</div><h2>Tester une API,<br /><em>sans quitter l’atelier.</em></h2><p>Reqly réunit les étapes au même endroit : tu prépares un appel, tu regardes la réponse, tu gardes tes essais dans des collections, puis tu peux relancer le tout avec le runner ou demander un coup de main à l’assistant IA.</p><div className="overview-actions"><Link href="/quickstart" className="action-button">Faire le premier essai <ArrowRight size={16} /></Link><Link href="/requests" className="quiet-action">Voir les possibilités <ArrowRight size={15} /></Link></div><div className="overview-signals"><span><i className="signal-green" /> Essayer</span><span><i className="signal-blue" /> Organiser</span><span><i className="signal-amber" /> Vérifier</span></div></div><div className="overview-art"><img src={asset.hero} alt="Atelier visuel Reqly" /><span>REST / GRAPHQL / SSE</span></div></div><div className="path-heading"><span>CE QUE TU VEUX FAIRE</span><span className="dashed-rule" /></div><div className="path-grid"><Link href="/quickstart" className="path-card coral-path"><small>01 · POUR COMMENCER</small><strong>Je veux voir<br />comment ça marche.</strong><span>6 min <ArrowRight size={15} /></span></Link><Link href="/collections" className="path-card lime-path"><small>02 · POUR M’ORGANISER</small><strong>Je veux retrouver<br />mes idées facilement.</strong><span>7 min <ArrowRight size={15} /></span></Link><Link href="/runs" className="path-card yellow-path"><small>03 · POUR ÊTRE SÛR</small><strong>Je veux vérifier une<br />collection en une passe.</strong><span>5 min <ArrowRight size={15} /></span></Link></div><div className="callout-note"><Zap size={17} /><p><strong>Besoin d’aide ?</strong> Chaque page commence par une situation concrète. Tu peux suivre le fil ou aller directement à ce que tu cherches.</p></div></>; }

function Quickstart() { return <><div className="mission-intro"><div className="mission-number">01</div><div><p>Objectif : faire un premier appel, regarder ce qui revient, puis sauvegarder la requête. Compte environ six minutes.</p><div className="inline-tags"><span>ORDINATEUR</span><span>PREMIER ESSAI</span><span>TRANQUILLE</span></div></div></div><div className="steps"><div className="step"><span>01</span><div><h3>Choisis ton espace</h3><p>En haut de l’atelier, le sélecteur d’espace de travail. « Mon espace » est local : tout reste chez toi tant que tu ne partages rien.</p></div></div><div className="step"><span>02</span><div><h3>Prépare un appel</h3><p>Choisis la méthode (GET par défaut) et renseigne l’adresse. Les sections Auth, Body, Params et Headers restent repliées jusqu’à ce que tu en aies besoin.</p></div></div><div className="step"><span>03</span><div><h3>Envoie et regarde</h3><p>Appuie sur <code>Ctrl+Entrée</code> ou sur Exécuter. La réponse s’affiche à droite : statut, temps, taille, puis les onglets Réponse, En-têtes, Cookies, Code, Tests et IA.</p></div></div><div className="step"><span>04</span><div><h3>Sauvegarde</h3><p>Appuie sur <code>Ctrl+S</code> pour nommer la requête et la ranger dans une collection. Tu la retrouveras plus tard.</p></div></div></div><RequestLab /><div className="after-lab"><Check size={16} /><p><strong>Tu as vu le principe.</strong> Continue avec <Link href="/collections">Garder ses idées ensemble</Link> pour retrouver facilement tes essais.</p></div></>; }

function Requests() { return <><div className="reference-banner"><Terminal size={19} /><div><strong>Préparer un appel, du début à la fin.</strong><span>Reqly garde l’objectif, les réglages et le résultat dans la même vue.</span></div><span className="status-pill">GUIDE</span></div><h2 className="content-h2">La même vue, de la méthode à la réponse.</h2><p className="content-paragraph">Tout se passe au centre de l’atelier : la barre d’URL, puis les sections repliables pour l’authentification, le corps, les paramètres et les en-têtes. Ce que tu règles reste visible, modifiable et relançable.</p><div className="method-table"><div className="method-row method-head"><span>SECTION</span><span>CE QUE TU RÈGLES</span><span>EXEMPLE</span></div>{[["URL + méthode","L’adresse et l’action","GET https://api.exemple.com/projets"],["Auth","Comment prouver qui tu es","Bearer, Basic, Clé API, OAuth 2.0"],["Body","Ce que tu envoies","JSON, brut, form-data, x-www-form"],["Params","Les variables de l’URL","/projets/{id}?page=1"],["Tests / Scripts","Ce que tu veux vérifier","pm.expect(...)"],["Headers","Les en-têtes personnalisés","Accept: application/json"]].map(([section, what, example]) => <div className="method-row" key={section}><span className="method-chip get">{section}</span><span>{what}</span><code>{example}</code></div>)}</div><h2 className="content-h2">Des variables pour ne rien répéter.</h2><p className="content-paragraph">Écris <code>{"{{BASE_URL}}"}</code> dans l’URL, les en-têtes ou le corps : Reqly le remplace par la valeur de l’environnement actif. Le panneau Variables te montre ce qui est résolu et ce qui ne l’est pas.</p><div className="plain-flow"><span>URL + méthode</span><ArrowRight size={14} /><span>Auth</span><ArrowRight size={14} /><span>Body</span><ArrowRight size={14} /><span>Exécuter</span><ArrowRight size={14} /><span>Lire la réponse</span></div></>; }

function Environments() { return <><div className="reference-banner lime-banner"><Layers3 size={19} /><div><strong>Changer d’espace, garder ton travail.</strong><span>Garde la même idée, puis passe de ton espace personnel à celui de ton équipe.</span></div><span className="status-pill">SIMPLE</span></div><h2 className="content-h2">Deux réglages de contexte.</h2><p className="content-paragraph">L’espace de travail détermine où vivent tes collections et tes environnements. L’environnement détermine quelles valeurs remplacent tes variables <code>{"{{...}}"}</code>.</p><div className="variable-board"><div className="variable-toolbar"><span>ESPACES DE TRAVAIL</span><span className="active-env"><i /> ACTUEL : MON ESPACE</span></div><div className="variable-row"><code>Mon espace</code><span>Local, non partagé</span><button><Check size={14} /></button></div><div className="variable-row"><code>Équipe produit</code><span>Partagé, invités</span><button onClick={() => toast.success("Espace équipe sélectionné.")}><ChevronRight size={14} /></button></div><div className="variable-row"><code>Présentation</code><span>Local, pour montrer une idée</span><button><ChevronRight size={14} /></button></div></div><div className="variable-board"><div className="variable-toolbar"><span>ENVIRONNEMENTS</span><span className="active-env"><i /> ACTUEL : LOCAL</span></div><div className="variable-row"><code>BASE_URL</code><span>https://api.exemple.com</span><button><Check size={14} /></button></div><div className="variable-row"><code>TOKEN</code><span className="masked">sk-••••••••••</span><button onClick={() => toast.success("Variable {{TOKEN}} copiée.")}><Copy size={14} /></button></div><div className="variable-row"><code>PAGE_SIZE</code><span>50</span><button><ChevronRight size={14} /></button></div></div><div className="plain-note"><KeyRound size={15} /><span>Une variable s’écrit <code>{"{{KEY}}"}</code> et se copie en un clic. Si une variable ne peut pas être résolue, Reqly te le signale avant l’envoi.</span></div></>; }

function Collections() { return <><div className="collection-layout"><div><div className="mission-badge"><span>PARCOURS 04</span><i /> RETROUVER</div><h2 className="content-h2">Tes requêtes restent là où tu les as laissées.</h2><p className="content-paragraph">Regroupe les essais d’un même projet en collection, range-les dans des dossiers et retrouve-les par recherche ou par méthode. Une collection sert à garder un fil, pas à ajouter du travail.</p><Link href="/runs" className="quiet-action">Vérifier une collection <ArrowRight size={15} /></Link></div><div className="collection-art"><img src={asset.orbit} alt="Organisation visuelle de projets Reqly" /><span>COLLECTION / DOSSIERS / REQUÊTES</span></div></div><div className="collection-tree"><div className="tree-root"><Layers3 size={15} /> Mon API <span>5 requêtes</span></div>{[["POST","Authentification","prêt"],["GET","Liste des projets","prêt"],["GET","Détail d’un projet","à reprendre"],["GET","Santé du service","prêt"],["GET","Statistiques","prêt"]].map(([method, item, state], index) => <div className="tree-item" key={item}><span className="tree-branch" /> <span className={`method-chip ${method === "POST" ? "post" : "get"}`}>{method}</span><strong>{item}</strong><small>{state}</small></div>)}</div><div className="plain-flow"><span>Ctrl+S sauvegarde</span><ArrowRight size={14} /><span>Recherche + filtre</span><ArrowRight size={14} /><span>Dossiers</span><ArrowRight size={14} /><span>Export OpenAPI</span></div></>; }

function Assertions() { return <><div className="reference-banner lime-banner"><CheckCircle2 size={19} /><div><strong>Savoir si tout va bien, sans lire la réponse en entier.</strong><span>Reqly transforme un résultat compliqué en quelques repères faciles à lire.</span></div><span className="status-pill">CLAIR</span></div><h2 className="content-h2">Des vérifications que tu choisis.</h2><p className="content-paragraph">Après l’exécution, chaque assertion donne un résultat : <code>réussite</code>, <code>échec</code>, <code>ignorée</code> ou <code>erreur</code>.</p><div className="assertion-cards"><div><span>01</span><strong>Statut</strong><p>La réponse doit répondre <code>200</code>.</p></div><div><span>02</span><strong>Temps de réponse</strong><p>Tout doit arriver en moins de <code>300 ms</code>.</p></div><div><span>03</span><strong>Chemin JSON</strong><p><code>data.items</code> doit exister ou contenir une valeur.</p></div></div><p className="content-paragraph">Le type <strong>Schéma</strong> compare la réponse entière à un schéma JSON. Et avec les scripts, tu peux récupérer une valeur pour la suite :</p><div className="code-block"><div className="code-block-head"><span>Script post-réponse (JS, sandboxé)</span><button onClick={() => { navigator.clipboard?.writeText("pm.expect(pm.response.code).to.equal(200);\npm.environment.set(\"token\", pm.response.json().token);"); toast.success("Script copié."); }}><Copy size={13} /> Copier</button></div><pre>{`pm.expect(pm.response.code).to.equal(200);
pm.environment.set("token", pm.response.json().token);`}</pre></div><div className="plain-checklist"><div><CheckCircle2 size={17} /><span>Le statut attendu est vérifié</span><b>OK</b></div><div><CheckCircle2 size={17} /><span>Le temps de réponse est vérifié</span><b>OK</b></div><div><CircleHelp size={17} /><span>Les chemins JSON et le schéma</span><b>OPTIONNEL</b></div></div><div className="run-result"><div><CheckCircle2 size={20} /><strong>Tout est prêt à être vérifié.</strong></div><button onClick={() => toast.success("Requête exécutée : toutes les assertions sont au vert.")}><Play size={14} fill="currentColor" /> Vérifier maintenant</button></div></>; }

function Runs() { return <><div className="reference-banner"><Play size={19} /><div><strong>Relancer toute une collection, en une passe.</strong><span>Chaque requête part dans l’ordre, chaque assertion est vérifiée.</span></div><span className="status-pill">AUTOMATIQUE</span></div><h2 className="content-h2">Le runner, étape par étape.</h2><p className="content-paragraph">Choisis une collection, règle l’environnement et le nombre d’itérations, lance : le runner exécute les requêtes séquentiellement et produit un rapport lisible.</p><div className="steps"><div className="step"><span>01</span><div><h3>Choisis une collection</h3><p>Le sélecteur liste tes collections sauvegardées, avec leur nombre de requêtes.</p></div></div><div className="step"><span>02</span><div><h3>Règle le contexte</h3><p>Environnement actif, itérations, et un jeu de données (JSON ou CSV) quand tu veux tester plusieurs valeurs.</p></div></div><div className="step"><span>03</span><div><h3>Lance la passe</h3><p>Les requêtes s’exécutent dans l’ordre. Chaque assertion donne une réussite, un échec, une ignorance ou une erreur.</p></div></div><div className="step"><span>04</span><div><h3>Lis le rapport</h3><p>Réussites, échecs, sautés, erreurs — et un export JUnit pour ta chaîne d’intégration continue.</p></div></div></div><div className="plain-flow"><span>Collection</span><ArrowRight size={14} /><span>Itérations</span><ArrowRight size={14} /><span>Jeu de données</span><ArrowRight size={14} /><span>Exécuter</span><ArrowRight size={14} /><span>Rapport</span></div><div className="plain-checklist"><div><CheckCircle2 size={17} /><span>Chaque assertion est vérifiée</span><b>OK</b></div><div><Table2 size={17} /><span>Jeu de données JSON ou CSV</span><b>OK</b></div><div><FileCode2 size={17} /><span>Export JUnit pour la CI</span><b>OPTIONNEL</b></div></div><div className="run-result"><div><CheckCircle2 size={20} /><strong>Une collection à vérifier ?</strong></div><button onClick={() => toast.success("Passage lancé : 6 réussites, 0 échec.")}><Play size={14} fill="currentColor" /> Exécuter la collection</button></div></>; }

function Integrations() { return <><div className="reference-banner"><Globe size={19} /><div><strong>Importer, exporter, travailler à plusieurs.</strong><span>Reqly parle les formats que ton équipe utilise déjà.</span></div><span className="status-pill">CONNECTER</span></div><h2 className="content-h2">Tout passe par des formats standards.</h2><p className="content-paragraph">Importe ce qui existe déjà, exporte pour les autres outils, et génère du code pour tes projets.</p><div className="generic-grid"><div><span className="number-tile">01</span><strong>Importer</strong><p>Collections Postman, spécifications OpenAPI, Bruno, GitLab, GitHub.</p></div><div><span className="number-tile">02</span><strong>Exporter</strong><p>OpenAPI, Postman, ou un fichier JSON de collection.</p></div><div><span className="number-tile">03</span><strong>Générer</strong><p>Des SDKs clients en Python, JavaScript, Go et plus.</p></div><div><span className="number-tile">04</span><strong>Capturer</strong><p>Le trafic HTTP devient des requêtes prêtes à tester.</p></div></div><div className="plain-checklist"><div><Download size={17} /><span>Importer une collection Postman</span><b>OK</b></div><div><Upload size={17} /><span>Exporter en OpenAPI ou Postman</span><b>OK</b></div><div><Boxes size={17} /><span>Générer un SDK client</span><b>OPTIONNEL</b></div><div><GitBranch size={17} /><span>Importer depuis GitLab ou GitHub</span><b>OPTIONNEL</b></div></div><div className="callout-note"><Zap size={17} /><p><strong>Travailler à plusieurs.</strong> Les espaces de travail partagés synchronisent tes collections avec ton équipe grâce à des liens d’invitation.</p></div></>; }

function Ai() { return <><div className="reference-banner"><Sparkles size={19} /><div><strong>Un assistant qui comprend ta requête et ta réponse.</strong><span>Il voit le contexte et propose ; tu restes maître de la décision.</span></div><span className="status-pill">ASSISTANT</span></div><h2 className="content-h2">Un coup de main, sans quitter l’atelier.</h2><p className="content-paragraph">Ouvre le panneau IA avec <code>Cmd+I</code>. L’assistant lit la requête, la réponse et les erreurs ; il propose, et tu décides.</p><div className="assertion-cards"><div><span>01</span><strong>Comprendre</strong><p>Résumer une réponse, expliquer un statut ou une erreur.</p></div><div><span>02</span><strong>Corriger</strong><p>Proposer un correctif quand une requête échoue.</p></div><div><span>03</span><strong>Automatiser</strong><p>Générer des assertions ou des tests à partir de la réponse.</p></div></div><div className="plain-flow"><span>Demander</span><ArrowRight size={14} /><span>L’assistant lit le contexte</span><ArrowRight size={14} /><span>Proposer</span><ArrowRight size={14} /><span>Appliquer</span></div><div className="plain-checklist"><div><Workflow size={17} /><span>Mode Plan : l’assistant propose, tu valides</span><b>OK</b></div><div><Shield size={17} /><span>Mode Act : il applique avec ton accord</span><b>OK</b></div><div><Sparkles size={17} /><span>Règles et permissions sous ton contrôle</span><b>OK</b></div></div><div className="callout-note"><Zap size={17} /><p><strong>Plusieurs fournisseurs.</strong> Anthropic, OpenAI, DeepSeek, Gemini et Ollama sont supportés. Tes clés restent dans tes paramètres.</p></div></>; }

function Desktop() { return <><div className="reference-banner"><Monitor size={19} /><div><strong>La même app sur ton bureau, même sans réseau.</strong><span>Une vraie fenêtre d’application, avec les mêmes raccourcis.</span></div><span className="status-pill">DESKTOP</span></div><h2 className="content-h2">Un atelier qui tient dans une fenêtre.</h2><p className="content-paragraph">Reqly tourne dans le navigateur ou en application de bureau (Windows, macOS, Linux). Même interface, même travail, mêmes fichiers.</p><div className="generic-grid"><div><span className="number-tile">01</span><strong>Bureau</strong><p>Une vraie fenêtre d’application, sans les onglets du navigateur.</p></div><div><span className="number-tile">02</span><strong>Hors ligne</strong><p>Les appels ratés partent en file d’attente et repartent au retour du réseau.</p></div><div><span className="number-tile">03</span><strong>Local</strong><p>Ton espace personnel reste sur ta machine tant que tu ne le partages pas.</p></div><div><span className="number-tile">04</span><strong>Confort</strong><p>Notifications, capture persistée sur disque, lancement rapide.</p></div></div><div className="plain-checklist"><div><Monitor size={17} /><span>Web et bureau : la même interface</span><b>OK</b></div><div><WifiOff size={17} /><span>File d’attente hors ligne</span><b>OK</b></div><div><Bell size={17} /><span>Notifications et capture sur disque</span><b>OPTIONNEL</b></div></div><div className="callout-note"><Zap size={17} /><p><strong>À retenir.</strong> Sur le bureau, la capture de trafic est sauvegardée sur disque et survit aux redémarrages.</p></div></>; }

function ReqlyJson() { return <><div className="reference-banner"><FileCode2 size={19} /><div><strong>Garder une copie de ton travail, la transmettre simplement.</strong><span>Des fichiers standards, lisibles partout et ré-importables.</span></div><span className="status-pill">EXPORT</span></div><h2 className="content-h2">Des fichiers standards, lisibles partout.</h2><p className="content-paragraph">Une collection s’exporte en JSON (par exemple <code>mon-api_collection.json</code>), ou en OpenAPI (<code>reqly-openapi.json</code>) pour les outils de ton équipe. Tu peux ensuite tout ré-importer.</p><div className="code-block"><div className="code-block-head"><span>mon-api_collection.json</span><button onClick={() => { navigator.clipboard?.writeText('{\n  "name": "Mon API",\n  "description": "Requêtes de démonstration",\n  "type": "collection",\n  "exportedAt": "2026-08-15T10:00:00.000Z",\n  "requests": [\n    { "name": "Liste des projets", "method": "GET", "url": "https://api.exemple.com/projets" }\n  ]\n}'); toast.success("JSON copié."); }}><Copy size={13} /> Copier</button></div><pre>{`{
  "name": "Mon API",
  "description": "Requêtes de démonstration",
  "type": "collection",
  "exportedAt": "2026-08-15T10:00:00.000Z",
  "requests": [
    { "name": "Liste des projets", "method": "GET", "url": "https://api.exemple.com/projets" }
  ]
}`}</pre></div><div className="plain-checklist"><div><Download size={17} /><span>Exporter une collection en JSON</span><b>OK</b></div><div><Upload size={17} /><span>Exporter en OpenAPI pour l’équipe</span><b>OK</b></div><div><Braces size={17} /><span>Ré-importer le fichier plus tard</span><b>OK</b></div></div><div className="plain-note"><CircleHelp size={15} /><span>Les snapshots REST permettent aussi de comparer deux réponses pour suivre l’évolution d’une API.</span></div></>; }

function PageBody({ page }: { page: Page }) { if (page.slug === "overview") return <Overview />; if (page.slug === "quickstart") return <Quickstart />; if (page.slug === "requests") return <Requests />; if (page.slug === "environments") return <Environments />; if (page.slug === "collections") return <Collections />; if (page.slug === "assertions") return <Assertions />; if (page.slug === "runs") return <Runs />; if (page.slug === "integrations") return <Integrations />; if (page.slug === "ai") return <Ai />; if (page.slug === "desktop") return <Desktop />; if (page.slug === "reqly-json") return <ReqlyJson />; return <GenericPage page={page} />; }

function GenericPage({ page }: { page: Page }) { return <><div className="reference-banner"><FileCode2 size={19} /><div><strong>{page.label}, simplement.</strong><span>Une page courte pour comprendre quand cette possibilité devient utile.</span></div><span className="status-pill">GUIDE</span></div><h2 className="content-h2">À quoi cela sert ?</h2><p className="content-paragraph">Reqly t’aide à garder le fil entre une idée, ce que tu essaies et ce que tu veux montrer. Commence par une petite action, puis ajoute du détail seulement quand tu en as besoin.</p><div className="generic-grid"><div><span className="number-tile">01</span><strong>Commencer</strong><p>Choisis une situation réelle, pas un exemple abstrait.</p></div><div><span className="number-tile">02</span><strong>Regarder</strong><p>Observe le résultat dans la même fenêtre.</p></div><div><span className="number-tile">03</span><strong>Continuer</strong><p>Garde ce qui fonctionne pour plus tard.</p></div></div></>; }

export default function Home() {
  const [, navigate] = useLocation();
  const [, params] = useRoute("/:slug");
  const slug = params?.slug ?? "overview";
  const page = getPage(slug);
  const [search, setSearch] = useState("");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [tocOpen, setTocOpen] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  const index = pages.findIndex((item) => item.slug === page.slug);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "/" && document.activeElement?.tagName !== "INPUT") { event.preventDefault(); searchRef.current?.focus(); } if (event.key === "Escape") { setMobileOpen(false); setTocOpen(false); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { setMobileOpen(false); window.scrollTo({ top: 0, behavior: "instant" as ScrollBehavior }); }, [slug]);
  useEffect(() => { if (search.trim()) { const first = pages.find((item) => `${item.label} ${item.description}`.toLowerCase().includes(search.toLowerCase())); if (first && first.slug !== slug) navigate(`/${first.slug}`); } }, [search]);
  const previous = pages[index - 1]; const next = pages[index + 1];
  return <main className="docs-root"><DocsSidebar slug={page.slug} search={search} setSearch={setSearch} mobileOpen={mobileOpen} closeMobile={() => setMobileOpen(false)} /><div className="docs-main"><DocsTopbar page={page} setMobileOpen={setMobileOpen} /><div className="docs-layout"><article className="docs-article"><PageHeader page={page} /><PageBody page={page} /><div className="page-nav">{previous ? <Link href={`/${previous.slug}`}><ArrowLeft size={15} /><span><small>PRÉCÉDENT</small><strong>{previous.label}</strong></span></Link> : <span />}{next ? <Link href={`/${next.slug}`}><span><small>SUIVANT</small><strong>{next.label}</strong></span><ArrowRight size={15} /></Link> : <span />}</div></article><aside className={`docs-toc ${tocOpen ? "is-open" : ""}`}><button className="toc-mobile-toggle" onClick={() => setTocOpen((value) => !value)}><span>Sur cette page</span><ChevronDown size={15} /></button><div className="toc-content"><span className="toc-title">SUR CETTE PAGE</span><a href="#top">Le point de départ</a><a href="#concept">Comment ça aide</a><a href="#example">Un exemple</a><a href="#next">La suite</a><div className="toc-tip"><Sparkles size={14} /><span>Tu peux suivre le parcours sans connaître les mots techniques.</span></div></div></aside></div></div><div className="docs-command"><Command size={13} /> <span><kbd>/</kbd> chercher · <kbd>esc</kbd> fermer</span></div></main>;
}